### ISSUE TITLE
KeyeError: Error Synchronizing Data:  'parentMagazineTitleId'

### ISSUE THREAD

**Issue by LoisGNS** [ping/libby-calibre-plugin#18]
See title. I had this error once before and it fixed itself on its own after a day. It came back, and it's been like this two days in a row. I'm using 0.1.9, which according to my plugin list, is the latest one.

**Comment by snachodog** [comment]
+1 started getting this error in the last week or so, but it's been a while since I specifically used this plugin.
Here is the output for the full error:

```
calibre 7.7  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre.exe
Successfully initialized third party plugins: DeACSM (0, 0, 16) && Gather KFX-ZIP (from KFX Input) (2, 9, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 9, 0) && Barnes & Noble (1, 5, 3) && Comicvine (0, 14, 2) && Embed Comic Metadata (1, 6, 6) && Extract ISBN (1, 6, 1) && Find Duplicates (1, 10, 9) && Generate Cover (2, 3, 4) && Goodreads (1, 8, 0) && Highlights to Obsidian (1, 4, 1) && Import List (1, 9, 2) && KFX metadata reader (from KFX Input) (2, 9, 0) && From KFX (2, 9, 0) && KFX Input (2, 9, 0) && Set KFX metadata (from KFX Output) (2, 7, 0) && KFX Output (2, 7, 0) && OverDrive Libby (0, 1, 9) && Quality Check (1, 13, 9) && Reading List (1, 15, 2) && ePub Extended Metadata {Writer} (0, 11, 2) && ePub Extended Metadata {Reader} (0, 11, 2) && ePub Extended Metadata (0, 11, 2)
Traceback (most recent call last):
  File "calibre_plugins.overdrive_libby.workers", line 432, in run
  File "calibre_plugins.overdrive_libby.workers", line 436, in <listcomp>
KeyError: 'parentMagazineTitleId'
```

**Comment by LoisGNS** [comment]
I received that error a while back. I traced it to a bad magazine subscription. In your calibre settings/plugins folder there is a file overdrive_libby.json. It will include entries like this for each magazine you are following:
  {
      "card_id": "xxxxxx",
      "parent_magazine_id": "xxxxx"
    },
Make a backup copy of the file and then start eliminating and restoring chunks of these entries, then retry until you find the bad entry/entries and restore the rest.
