### ISSUE TITLE
Error regarding data time formats

### ISSUE THREAD

**Issue by p1nkyy** [ping/libby-calibre-plugin#20]
Hello, today (Feb 6) I encountered repeated errors when downloading certain ebooks. Here are the logs:

```
calibre, version 7.4.0
ERROR: Unhandled exception: <b>ValueError</b>: Failed to download e-book

calibre 7.4  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: ACSM Input (0, 1, 0) && DeDRM (10, 0, 3) && ACSM Input Plugin GUI Extension (0, 1, 0) && Find Duplicates (1, 10, 8) && KindleUnpack - The Plugin (0, 83, 1) && Modify ePub (1, 8, 2) && OverDrive Libby (0, 1, 9)
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.overdrive_libby.ebook_download", line 59, in __call__
  File "calibre_plugins.overdrive_libby.download", line 253, in add
  File "calibre_plugins.overdrive_libby.download", line 97, in update_metadata
  File "calibre_plugins.overdrive_libby.libby.client", line 337, in parse_datetime
ValueError: time data '2024-02-06T00:00:00' does not match known formats ('%Y-%m-%dT%H:%M:%SZ', '%Y-%m-%dT%H:%M:%S.%fZ', '%Y-%m-%dT%H:%M:%S%z', '%Y-%m-%dT%H:%M:%S.%f%z', '%m/%d/%Y')
```

Also when I try to re-download the book from my Loan list, it still failed but it doesn't appear in the Loan List at all. Can we get a list of books that aren't able to be processed or downloaded due to a problem? Thanks so much.

@ping

**Comment by reedstrm** [comment]
I'm hitting the same error, after adding a card for a new library. Seems they're not putting the timezone on their timestamps (which look to be dates extended to timestamp with zeros)
 I can confirm that PR  #17  works on my machine to solve this issue.
