### ISSUE TITLE
Client Connection Error when entering Libby setup code v0.1.9

### ISSUE THREAD

**Issue by stonie08** [ping/libby-calibre-plugin#23]
I tried to setup the plugin (v0.1.9) with the 8-digit libby setup code. However, after entering the code and pressing OK I get an error due to an unhandled exception for an expired certificate. It doesn't say which URL it tried to connect or anything. Unfortunately, there's no way around the setup code, so I'm pretty much stuck there.

The full error message after pressing "Copy to clipboard" in the error dialogue:
```
calibre, version 7.8.0
ERROR: Unhandled exception: <b>ClientConnectionError</b>:&lt;calibre_plugins.overdrive_libby.libby.errors.ClientConnectionError; http_status=0, msg='URLError &lt;urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1006)&gt;', error_response='''&gt;

calibre 7.8 Portable embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: D:\Calibre\Calibre Portable\Calibre\calibre.exe
Successfully initialized third party plugins: OverDrive Libby (0, 1, 9)
Traceback (most recent call last):
  File "urllib\request.py", line 1348, in do_open
  File "http\client.py", line 1286, in request
  File "http\client.py", line 1332, in _send_request
  File "http\client.py", line 1281, in endheaders
  File "http\client.py", line 1041, in _send_output
  File "http\client.py", line 979, in send
  File "http\client.py", line 1458, in connect
  File "ssl.py", line 517, in wrap_socket
  File "ssl.py", line 1108, in _create
  File "ssl.py", line 1379, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.overdrive_libby.libby.client", line 518, in send_request
  File "urllib\request.py", line 519, in open
  File "urllib\request.py", line 536, in _open
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 1391, in https_open
  File "urllib\request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1006)>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibre_plugins.overdrive_libby.action", line 133, in <lambda>
  File "calibre\customize\__init__.py", line 188, in do_user_config
  File "calibre_plugins.overdrive_libby.__init__", line 104, in save_settings
  File "calibre_plugins.overdrive_libby.config", line 947, in save_settings
  File "calibre_plugins.overdrive_libby.libby.client", line 593, in get_chip
  File "calibre_plugins.overdrive_libby.libby.client", line 556, in send_request
calibre_plugins.overdrive_libby.libby.errors.ClientConnectionError: <calibre_plugins.overdrive_libby.libby.errors.ClientConnectionError; http_status=0, msg='URLError <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1006)>', error_response='''>

```

**Comment by stonie08** [comment]
Solved, I missed the FAQ mentioning the issue: https://github.com/ping/libby-calibre-plugin?tab=readme-ov-file#ssl-certificate_verify_failed-certificate-verify-failed-error-on-windows
