### ISSUE TITLE
ClientForbiddenError: Error synchronizing data (HTTP Error 403: Forbidden)

### ISSUE THREAD

**Issue by ashunn** [ping/libby-calibre-plugin#25]
Recently, OverDrive Libby has stopped working. The following error message is being thrown when I open or try to refresh the OverDrive Libby plugin:

```
calibre, version 7.9.0
ERROR: Unhandled exception: <b>ClientForbiddenError</b>: Error synchronizing data<p>HTTP Error 403: Forbidden</p>

calibre 7.9  embedded-python: True
Windows-10-10.0.22635-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22635')
Python 3.11.5
Windows: ('10', '10.0.22635', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 10, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (2, 10, 0) && APNX Generator (1, 1, 0) && Audio M3U (1, 0, 0) && Check Books (0, 1, 8) && Count Pages (1, 13, 6) && Editor Chains (1, 1, 6) && English Noun Frequency (1, 0, 16) && EpubCheck (0, 2, 5) && Highlights to Obsidian (1, 4, 1) && Hyphenate This! (0, 1, 3) && KFX metadata reader (from KFX Input) (2, 10, 0) && From KFX (2, 10, 0) && KFX Input (2, 10, 0) && Set KFX metadata (from KFX Output) (2, 7, 0) && KFX Output (2, 7, 0) && Kindle Collections (1, 7, 29) && Kindle hi-res covers (0, 5, 1) && KindleUnpack - The Plugin (0, 83, 1) && Last Modified (0, 8, 5) && OverDrive Libby (0, 1, 9) && Quality Check (1, 13, 10) && Reformat plugin (2, 4, 0) && TextDiff (1, 2, 4) && WordDumb (3, 31, 2) && X-Ray Creator (3, 2, 1)
Traceback (most recent call last):
  File "calibre_plugins.overdrive_libby.libby.client", line 518, in send_request
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 634, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 643, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibre_plugins.overdrive_libby.workers", line 351, in run
  File "calibre_plugins.overdrive_libby.libby.client", line 631, in sync
  File "calibre_plugins.overdrive_libby.libby.client", line 538, in send_request
  File "calibre_plugins.overdrive_libby.libby.errors", line 143, in process
calibre_plugins.overdrive_libby.libby.errors.ClientForbiddenError: <calibre_plugins.overdrive_libby.libby.errors.ClientForbiddenError; http_status=403, msg='HTTP Error 403: Forbidden', error_response='{"result":"missing_chip"}''>
```

**Comment by p1nkyy** [comment]
Re-connect your Libby to the plugin. Go to Customize Plugin and add new Libby Setup Code.

**Comment by reedstrm** [comment]
> Re-connect your Libby to the plugin. Go to Customize Plugin and add new Libby Setup Code.

Thanks this helped me - for those who haven't done it in a while, setting in the android libby app are down at the bottom of the notifications pane (the central the lines stacked icon).

**Comment by p1nkyy** [comment]
Kindly close the issue if it's resolved 🙂
