### ISSUE TITLE
Libby Setup Code

### ISSUE THREAD

**Issue by studiosusmed** [ping/libby-calibre-plugin#30]
The code won't show after setting it up. Is there another way to get the code?

cheers and thx for your work!

**Comment by meljadyn** [comment]
To provide more detail (assuming you're talking about what I've noticed as well)

It seems like Libby has changed their set up code process. Now instead of generating the code on the original device and copying it to the new device, Libby generates the code on the new device and copies it to the old one. That means that there's no way to properly connect this plugin with Libby unless it generate its own code. 

Libby has a couple legacy options for Sonos speakers or Android Automotive, but I couldn't get the plugin to work using either of those options.

They are mostly vouching for the recovery passkey system now instead of codes and the code options available don't seem compatible with this plugin.

See more information here: [Libby Help Page | Setting up Libby on another device](https://help.libbyapp.com/en-us/6070.htm)

**Comment by sgmoore** [comment]
Setup codes have not worked with this plugin for a while. 
Libby have changed the way their webservers work (even before this recent change) and parts of this plugin no longer work, including authentication (or setup) and the ability to download books and magazines.

You can still do some things including search, borrow and return books (which makes the plugin still useful for me)

To get around the authentication you need to get a token using the workaround detailed here 
https://www.mobileread.com/forums/showpost.php?p=4419260&postcount=134

You also need to open the plugin at least once for it to create an mostly empty json file, 

To find out where it is created, in calibre click on Preferences: Misc...  and 'Open calibre configuration directory' and switch into the plugins folder. The file should be called overdrive_libby.json and can be edited by any text editor.

You need to close calibre before you edit this file.

This may look something like

```
{
  "main_ui_height": 554
}
```

You need to edit this file and add two lines at the start

```
{
  "libby_setup_code": "00000000",
  "libby_token": "xxx",
  "main_ui_height": 554
}
```
You need to replace the xxx in the above example to be your token obtained from your browser.

One tip is that if your copied token starts or ends with ... , that is usually your browser not showing you the whole token and will not work.

Then save the file and restart calibre.

The token expires after about a week. It would appear to be renewed if you regularly use this plugin, but if not, then you may need to get another token and update your overdrive_libby.json file.

**Comment by FirstHurdle** [comment]
I Uninstalled the plugin. uninstalled calibre. Deleted the Calibre folders in Appdata and stated from scratch

On Libby website on the Copy To Another Device option there was a code available for Sonos Speakers or Android Automative (the same code). I tried using that and got further - I can now see, through the libby plugin, the list of items I have on loan from the library.

The next obstacle is that when I try and download any of the magazines I have on loan I get another error


calibre, version 7.16.0
ERROR: Unhandled exception: <b>KeyError</b>: Failed to download e-book

calibre 7.16  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre.exe
Successfully initialized third party plugins: OverDrive Libby (0, 1, 9)
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 85, in start_work
  File "calibre_plugins.overdrive_libby.magazine_download", line 387, in __call__
  File "calibre_plugins.overdrive_libby.magazine_download", line 467, in _custom_download
  File "calibre_plugins.overdrive_libby.libby.client", line 822, in process_ebook
KeyError: 'openbook'

**Comment by studiosusmed** [comment]
> I Uninstalled the plugin. uninstalled calibre. Deleted the Calibre folders in Appdata and stated from scratch
> 
> On Libby website on the Copy To Another Device option there was a code available for Sonos Speakers or Android Automative (the same code). I tried using that and got further - I can now see, through the libby plugin, the list of items I have on loan from the library.
> 
> The next obstacle is that when I try and download any of the magazines I have on loan I get another error
> 
> calibre, version 7.16.0 ERROR: Unhandled exception: KeyError: Failed to download e-book
> 
> calibre 7.16 embedded-python: True Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE') ('Windows', '10', '10.0.19045') Python 3.11.5 Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free') Interface language: None EXE path: C:\Program Files\Calibre2\calibre.exe Successfully initialized third party plugins: OverDrive Libby (0, 1, 9) Traceback (most recent call last): File "calibre\gui2\threaded_jobs.py", line 85, in start_work File "calibre_plugins.overdrive_libby.magazine_download", line 387, in **call** File "calibre_plugins.overdrive_libby.magazine_download", line 467, in _custom_download File "calibre_plugins.overdrive_libby.libby.client", line 822, in process_ebook KeyError: 'openbook'

Thx! The way with the Sonos Speakers worked flawlessly for me.
