### ISSUE TITLE
error 'HTTP Error 403: Forbidden', error_response='{"result":"missing_chip"}''>

### ISSUE THREAD

**Issue by FirstHurdle** [ping/libby-calibre-plugin#31]
Installed 64bit calibre. Installed 1.9 plugin. Click on generate setup code and I see the error message

calibre, version 7.16.0
ERROR: Unhandled exception: <b>ClientForbiddenError</b>:&lt;calibre_plugins.overdrive_libby.libby.errors.ClientForbiddenError; http_status=403, msg='HTTP Error 403: Forbidden', error_response='{"result":"missing_chip"}''&gt;

calibre 7.16  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre.exe
Successfully initialized third party plugins: OverDrive Libby (0, 1, 9)
Traceback (most recent call last):
  File "calibre_plugins.overdrive_libby.libby.client", line 518, in send_request
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 634, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 643, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibre_plugins.overdrive_libby.config", line 706, in generate_code_btn_clicked
  File "calibre_plugins.overdrive_libby.libby.client", line 622, in generate_clone_code
  File "calibre_plugins.overdrive_libby.libby.client", line 538, in send_request
  File "calibre_plugins.overdrive_libby.libby.errors", line 143, in process
calibre_plugins.overdrive_libby.libby.errors.ClientForbiddenError: <calibre_plugins.overdrive_libby.libby.errors.ClientForbiddenError; http_status=403, msg='HTTP Error 403: Forbidden', error_response='{"result":"missing_chip"}''>

**Comment by sgmoore** [comment]
See https://github.com/ping/libby-calibre-plugin/issues/30

**Comment by andreshincapier** [comment]
You can see my comment here 👉 #27. I experienced the same error
