### ISSUE TITLE
Can't download magazines from libby - "KeyError: Failed to download e-book".

### ISSUE THREAD

**Issue by FirstHurdle** [ping/libby-calibre-plugin#32]
Has anyone succeeded in downloading any magazines from libby?  
When I try and download any of the magazines I have on loan I get this error: -

calibre, version 7.16.0
ERROR: Unhandled exception: KeyError: Failed to download e-book

calibre 7.16 embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre.exe
Successfully initialized third party plugins: OverDrive Libby (0, 1, 9)
Traceback (most recent call last):
File "calibre\gui2\threaded_jobs.py", line 85, in start_work
File "calibre_plugins.overdrive_libby.magazine_download", line 387, in call
File "calibre_plugins.overdrive_libby.magazine_download", line 467, in _custom_download
File "calibre_plugins.overdrive_libby.libby.client", line 822, in process_ebook
KeyError: 'openbook'

**Comment by sgmoore** [comment]
Not since around April when they changed their servers.

You can still download ebooks from the libbyapp and overdrive websites, but there does not seem to be any way to download magazines.
