### ISSUE TITLE
TypeError: None is not a unicode string

### ISSUE THREAD

**Issue by ping** [ping/libby-calibre-plugin#9]
````
calibre, version 6.25.0
ERROR: Unhandled exception: <b>TypeError</b>:None is not a unicode string

calibre 6.25  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: ACSM Input (0, 1, 0) && DeDRM (10, 0, 3) && ACSM Input Plugin GUI Extension (0, 1, 0) && KindleUnpack - The Plugin (0, 83, 1) && Modify ePub (1, 8, 1) && OverDrive Libby (0, 1, 7)
Traceback (most recent call last):
  File "calibre_plugins.overdrive_libby.models", line 772, in filterAcceptsRow
  File "calibre\utils\icu.py", line 191, in change_case
TypeError: None is not a unicode string
`````

Trying to type in something in the Filter bar in Cards tab generates an error.

@ping

_Originally posted by @p1nkyy in https://github.com/ping/libby-calibre-plugin/issues/7#issuecomment-1694619744_

**Comment by ping** [comment]
@p1nkyy This should be fixed by d8df1b2e5832ca65304d53b8b01f35379e777427

[overdrive-libby-plugin-d8df1b2.zip](https://github.com/ping/libby-calibre-plugin/suites/15529449708/artifacts/886425819)
